//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StardestroyerBetaKLABUD.ServiceOldBay {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Wing", Namespace="http://schemas.datacontract.org/2004/07/ModelsKLABUD")]
    [System.SerializableAttribute()]
    public partial class Wing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shield {
            get {
                return this.ShieldField;
            }
            set {
                if ((this.ShieldField.Equals(value) != true)) {
                    this.ShieldField = value;
                    this.RaisePropertyChanged("Shield");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceOldBay.IOldBayKLABUD")]
    public interface IOldBayKLABUD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOldBayKLABUD/GetWing", ReplyAction="http://tempuri.org/IOldBayKLABUD/GetWingResponse")]
        StardestroyerBetaKLABUD.ServiceOldBay.Wing GetWing(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOldBayKLABUD/CreateWing", ReplyAction="http://tempuri.org/IOldBayKLABUD/CreateWingResponse")]
        string CreateWing(StardestroyerBetaKLABUD.ServiceOldBay.Wing wing);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOldBayKLABUD/GetAllWings", ReplyAction="http://tempuri.org/IOldBayKLABUD/GetAllWingsResponse")]
        System.Collections.Generic.List<StardestroyerBetaKLABUD.ServiceOldBay.Wing> GetAllWings();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOldBayKLABUDChannel : StardestroyerBetaKLABUD.ServiceOldBay.IOldBayKLABUD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OldBayKLABUDClient : System.ServiceModel.ClientBase<StardestroyerBetaKLABUD.ServiceOldBay.IOldBayKLABUD>, StardestroyerBetaKLABUD.ServiceOldBay.IOldBayKLABUD {
        
        public OldBayKLABUDClient() {
        }
        
        public OldBayKLABUDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OldBayKLABUDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OldBayKLABUDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OldBayKLABUDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StardestroyerBetaKLABUD.ServiceOldBay.Wing GetWing(string name) {
            return base.Channel.GetWing(name);
        }
        
        public string CreateWing(StardestroyerBetaKLABUD.ServiceOldBay.Wing wing) {
            return base.Channel.CreateWing(wing);
        }
        
        public System.Collections.Generic.List<StardestroyerBetaKLABUD.ServiceOldBay.Wing> GetAllWings() {
            return base.Channel.GetAllWings();
        }
    }
}
